### ISSUE TITLE
More coins integration

### ISSUE THREAD

**Issue by gaurav99t** [cryptoapi/Payment-Gateway#10]
How can i add these coins to the list of coins for payment?

bitcoin
ripple
etherum
dogecoin
tattoocoin (tse)
tattoocoin (tle)
etherum clasic
lisk
litecoin
monero

**Comment by cryptoapi** [comment]
If you want to add any supported cryptocoin to GoUrl Cryptocurrency Payment Gateway you will need to vote - https://gourl.io/coin-voting.html
