### ISSUE TITLE
Private Keys Issues

### ISSUE THREAD

**Issue by michaelsomerville** [cryptoapi/Payment-Gateway#12]
When using a multi-user environment, as you've outline in your examples. Where we have our members get their own public/private keys from gourl and save them in our site.

The code is calling the key from *.config.php and making an error, how is it possible to code is call out of the process and also, why are you calling the key from the config if we are putting them in the code at the time of creating the payment anyways.

This is the call ... 

		if (!defined("CRYPTOBOX_PRIVATE_KEYS") || !in_array($this->private_key, explode("^", CRYPTOBOX_PRIVATE_KEYS))) die("Error. Please add your Cryptobox Private Key ".(CRYPTOBOX_WORDPRESS ? "on your plugin settings page" : "to \$cryptobox_private_keys in file cryptobox.config.php"));

Here's what I did .. but apparently we're stupid and it doesn't work all the time.

```
$allkeys = run_sql('select * from `coinblock_usersettings`');

$cryptobox_private_keys = array();

foreach ($allkeys as $a){ $cryptobox_private_keys[] = $a->privateKey; }

define("CRYPTOBOX_PRIVATE_KEYS", implode("^", $cryptobox_private_keys));
unset($cryptobox_private_keys); 

```

**Comment by cryptoapi** [comment]
**Correct is -**

	$allkeys = run_sql('select * from `coinblock_usersettings`');
	
	**if ($allkeys && !is_array($allkeys)) $allkeys = array($allkeys); // single record in table coinblock_usersettings **

	$cryptobox_private_keys = array();

	foreach ($allkeys as $a){ $cryptobox_private_keys[] = $a->privateKey; }

	define("CRYPTOBOX_PRIVATE_KEYS", implode("^", $cryptobox_private_keys));
	unset($cryptobox_private_keys); 

	**include('cryptobox.class.php');**

**Comment by michaelsomerville** [comment]
Why did you add the  include('cryptobox.class.php') that's not in the file as is.
