### ISSUE TITLE
Version 1.8.1 (August 2017)

### ISSUE THREAD

**Issue by michaelsomerville** [cryptoapi/Payment-Gateway#13]
Awesome update and thanks for jumping on this so quick! What are you using for a wallet / storage ? Still trying to find something that works good. 

Mike.

**Comment by cryptoapi** [comment]
Bitcoin ABC Wallet - https://download.bitcoinabc.org/0.14.6/

Bitcoin Unlimited Cash Release - https://www.bitcoinunlimited.info/download

**Comment by michaelsomerville** [comment]
Why do you close these so fast, lol.
How are you feelings right now with bitcoin cash - been 24 hours on one of transactions and only have 13 confirmations. Seems like there isn't enough hashing.
