### ISSUE TITLE
User Payments Issue

### ISSUE THREAD

**Issue by michaelsomerville** [cryptoapi/Payment-Gateway#14]
I am using the user/user payment system with PHP ... our users input their keys etc just like outline in your code. It all works, but we've been had issues with some users IPN webhook not pushing back. Is there a way to confirm a webhook is like with users api keys or gather data with users api keys ? 

Basically, we have people that have paid but the user is not getting back to us and letting us know if payment was confirmed or not. Otherwise, if the webhook worked it would have reported.

Thanks!!

**Comment by cryptoapi** [comment]
Our gateway automatically re-send IPN data until receive successful response from seller server. You can [send us](https://gourl.io/view/contact/Contact_Us.html) transaction IDs and we will send you IPN data status for that transactions.

IPN instruction - https://gourl.io/api-php.html#ipn

If you use Cloudflare & Mod_Security & other CDN services, please add our server IPs in Whitelist.
Our Server IPs:   51.255.140.174 & 51.254.199.21   and IPv6:   2001:41d0:1008:b15:b174::1 & 2001:41d0:1008:b15:b21::1

**Comment by michaelsomerville** [comment]
No, the user just didn't had the callback url to the payment box - there not a way to check with the api information ?

**Comment by cryptoapi** [comment]
No other way. GoUrl Gateway work in automatic mode.
