### ISSUE TITLE
Google Currency Live function has been a issue for the past few days

### ISSUE THREAD

**Issue by gabisajr** [cryptoapi/Payment-Gateway#16]
as for me I had to change the function to use the  code below, hope it helps someone else

```
$url = "http://currencies.apps.grandtrunk.net/getlatest/".$from_Currency.'/'.$to_Currency;
try 
{
    $ch = curl_init();
    curl_setopt ($ch, CURLOPT_URL, $url);
    curl_setopt( $ch, CURLOPT_SSL_VERIFYPEER, FALSE);
    curl_setopt ($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt ($ch, CURLOPT_USERAGENT, "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)");
    curl_setopt ($ch, CURLOPT_CONNECTTIMEOUT, 20);
    curl_setopt ($ch, CURLOPT_TIMEOUT, 20);
    $rawdata = curl_exec($ch);
    curl_close($ch);
    if(is_numeric($rawdata)){
        $amount = ($rawdata * $amount);
    }else{
        $amount = 0;
    }
    return round($amount, 2);
} 
catch (Exception $e){
    $amount = 0;
    return round($amount, 2);
}
```

**Comment by cryptoapi** [comment]
thank you

**Comment by sadue** [comment]
@gabisajr I want to disable the use of external currency converter and set my own exchange rate. Someone sugested this to me today
`function convert_currency_live($from_Currency, $to_Currency, $amount)
{
    $amount = urlencode($amount);
    $from_Currency = trim(strtoupper(urlencode($from_Currency)));
    $to_Currency = trim(strtoupper(urlencode($to_Currency)));

    if($from_Currency == "NGN" && $to_Currency == "USD"){
        return round(($amount * 376), 2);
    }else{

        if ($from_Currency == "TRL")  $from_Currency = "TRY"; // fix for Turkish Lyra
        if ($from_Currency == "ZWD")  $from_Currency = "ZWL"; // fix for Zimbabwe Dollar
        if ($from_Currency == "RIAL") $from_Currency = "IRR"; // fix for Iranian Rial

        $url = "https://finance.google.com/finance/converter?a=".$amount."&amp;from=".$from_Currency."&amp;to=".$to_Currency;

        $ch = curl_init();
        curl_setopt ($ch, CURLOPT_URL, $url);
        curl_setopt( $ch, CURLOPT_SSL_VERIFYPEER, FALSE);
        curl_setopt ($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt ($ch, CURLOPT_USERAGENT, "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko");
        curl_setopt ($ch, CURLOPT_CONNECTTIMEOUT, 20);
        curl_setopt ($ch, CURLOPT_TIMEOUT, 20);
        $res = curl_exec($ch);
        curl_close($ch);

        if ($res)
        {
            $data = explode('bld&gt;', $res);
            $data = explode($to_Currency, $data[1]);
            return round($data[0], ($to_Currency=="BTC"?5:2));
        }else{
            return -1; 
        }
    }`
What do you think?

**Comment by cryptoapi** [comment]
It is open source bitcoin library. You can modify it.
