### ISSUE TITLE
Error in Cryptobox.class.php

### ISSUE THREAD

**Issue by Belladona-c0re** [cryptoapi/Payment-Gateway#17]
Source Downloaded.
Public and Private key Editeds.
Database configured. 

PHP Parse error:  syntax error, unexpected '[' in /var/www/Payment-Gateway/cryptobox.class.php on line 1087

Any idea ?

**Comment by cryptoapi** [comment]
Update php to 5.6+

This is line - 
https://github.com/cryptoapi/Payment-Gateway/blob/master/cryptobox.class.php#L1087
