### ISSUE TITLE
Deposits and Fees don't seem to be right at all now!

### ISSUE THREAD

**Issue by michaelsomerville** [cryptoapi/Payment-Gateway#18]
Emailed support, haven't heard back! Am I the only one that seems to be seeing 10% fees on transactions now. I don't have a clue what is going on! They say 1.5% but it's like literally 10.3% now.

Some information on this would be great, we are processing a lot of transactions.

**Comment by cryptoapi** [comment]
Your account have 1.5% gourl fees. Also you pay bitcoin network fees when payment transfer to your external bitcoin wallet address. Avera bitcoin network transaction fees are $20-$150 per transaction, please use bitcoin cash/dash as alternative.

Our tweet - https://twitter.com/CryptocoinAPI/status/931673064340951042

**Comment by michaelsomerville** [comment]
Yes, I understand that - but when a transaction is 0.05 and you add 0.045 to the account - something is off. You then send 0.042 to my external wallet. Looking at the mining fee its only 30.00ish. So, please either look at your code for errors or explain this in more than just that type of comment. Love the service, tell lots of people about it - but there needs to be more transparencies

**Comment by cryptoapi** [comment]
You need to see general payment box summary, not per transaction. Sometimes your account can be in credit.

**Comment by michaelsomerville** [comment]
What do you mean by in credit ? I have compare the account and see that the fees are more than 1.5% that's why I am saying there is something wrong.

**Comment by cryptoapi** [comment]
if  your last transaction fees was bigger than expected.

For example you had on account 1 BTC, 
bitcoin daemon sent to you 0.9845 BTC  + expected 0.0005 BTC  transaction fees. 
Real transaction fees was 0.0007 BTC , 
and therefore you account balance is -0.0002 BTC

Please contact us https://gourl.io/view/contact/Contact_Us.html

**Comment by michaelsomerville** [comment]
I have sent many emails ... Your correct with the above the problem is, when someone pays 0.05 BTC you are only crediting the account 0.04572 at the moment. By the time it get's to our wallet it is 0.0425 - doesn't add up.

**Comment by michaelsomerville** [comment]
Looks like the change the 1.5% to 3.5% when you process a lot of bitcoin. I had all my payment boxes set to not gambling or sex sites and it changed them all. You can't change them back either, the system doesn't apparently work right.

I have sent video and images to support to prove this - seems like no one is getting back to me about this. Not a good look, I promote your site to many people without an affiliate link and use the service for our large membership site. Please get this glitch fixed!!
