### ISSUE TITLE
Sandboxs

### ISSUE THREAD

**Issue by migueltarga** [cryptoapi/Payment-Gateway#2]
How can I test my code?

**Comment by cryptoapi** [comment]
**Testing environment**

You can use Speedcoins or Dogecoins for testing. 
You can get 110 free speedcoins here http://speedcoin.co/info/free_coins/Free_Speedcoins.html 

The minimum account balance on GoUrl.io which our system will automatically transfer from your GoUrl internal wallet address to your external wallet address is 2 x mining fee. For Bitcoin this is 0.0005 BTC, and for Speedcoin and Dogecoin it is 5 coins, etc
