### ISSUE TITLE
IPN Testing

### ISSUE THREAD

**Issue by Matt0000** [cryptoapi/Payment-Gateway#20]
Hello, 

Is it possible to do a test IPN so that I can confirm if my server handles everything properly wihtout having to actually buy some crypto just to test this?

**Comment by michaelsomerville** [comment]
They recommend using a free or cheap coin, but I just use the json data and curl it to my webhooks. Works great!

**Comment by cryptoapi** [comment]
Please use free speedcoins https://gourl.io/api-php.html#testing
