### ISSUE TITLE
Ipn issue

### ISSUE THREAD

**Issue by NoorBolbol** [cryptoapi/Payment-Gateway#27]
I've integrated the API with codeigniter framework
Everything is going good but the second call for callback url is not firing 
I have to reload the page after the payment confirmed to get response from gourl (to check it as confirmed on db) 
I use Ajax so it should fired automatically ?

**Comment by OratorEse** [comment]
Maybe

**Comment by cryptoapi** [comment]
When payment confirmed, GoUrl server send data through IPN url (https://gourl.io/images/paymentbox6.png)

https://gourl.io/api-php.html#ipn

**Comment by noblesomto** [comment]
> I've integrated the API with codeigniter framework Everything is going good but the second call for callback url is not firing I have to reload the page after the payment confirmed to get response from gourl (to check it as confirmed on db) I use Ajax so it should fired automatically ?

Please, how did you integrate it?
