### ISSUE TITLE
Not forwarding coin

### ISSUE THREAD

**Issue by seunex17** [cryptoapi/Payment-Gateway#30]
Gourl look like a scarn I. Have up to 70$ worth of btc I prove my wallet address Multiple time still not forwarding my coin support is not replying look like a scarm

**Comment by cryptoapi** [comment]
Our system forwards ALL received confirmed bitcoin payments (6+ confirmations, recognized & unrecognized payments) to your external wallet automatically every 30 minutes when the balance on your bitcoin account is 0.01 BTC or more.

Sometimes the bitcoin network transaction fees when bitcoin payment is forwarded to user external wallet address  are bigger than the outstanding balance on the user’s payment box.
Therefore we have provided a minimal amount for auto withdrawal.

Unfortunately we can only manually process all outstanding balances from all user payment boxes when user close his gourl account. Please confirm it https://gourl.io/view/contact/Contact_Us.html
Our system does not allow us to do this in any other way.


Please use Bitcoin Cash for small payments (bitcoin cash minimum forward amount is 0.0005 BCH;  i.e. 20 times less than bitcoin minimum amount)!

**Comment by seunex17** [comment]
Support is not replying I have ci tact support 5 times now I got no respond.

**Comment by cryptoapi** [comment]
Your payment box balance is 0.00866762 BTC
It should be 0.01 BTC or more for auto forward to your external wallet address.

Unfortunately we can only manually process all outstanding balances from all user payment boxes when user close his gourl account. **Please confirm it**
Our system does not allow us to do this in any other way.
