### ISSUE TITLE
Failing on cryptobox.callback.php part

### ISSUE THREAD

**Issue by cryptopool-builders** [cryptoapi/Payment-Gateway#31]
Hello all, so I am working on setting this up and I am having issues getting the cryptobox.callback.php and cryptobox.newpayment.php to work properly as of right now I am getting a 404 error when going to the cryptobox.callback.php file. 

The error is `PHP message: PHP Parse error:  syntax error, unexpected '{', expecting '(' in /lib/cryptobox.newpayment.php on line 86"`

ive read every page i could find and im sure the issue is something to with how the newpayment file is setup. can you please post exactly how its supposed to work with functioning code?

**Comment by cryptoapi** [comment]
In original file - no any code in line 86. 
https://github.com/cryptoapi/Payment-Gateway/blob/master/lib/cryptobox.newpayment.php#L86

Looking like you added new own php code. Please check it.
