### ISSUE TITLE
Only once sell

### ISSUE THREAD

**Issue by justinbiebermusic** [cryptoapi/Payment-Gateway#32]
How can I make pay per download system is like only once sell. If someone download it it should be expired and should say for the all other people "SOLD" so they can't buy it again.

**Comment by cryptoapi** [comment]
You can manually check in PHP if payment for this product has already been received.
In Wordpress - please use WooCommerce

**Comment by justinbiebermusic** [comment]
It's not a solution man. if you have 1000 file for sell. and if each will be sold only once. it's so hard. I'm looking for smth like that.

file name : x.zip

if someone already bought x.zip. other people will see "IT'S SOLD".

if it's not possible. I'll create an php file like sold.php. they should auto see sold.php

**Comment by cryptoapi** [comment]
Do you use wordpress or php ?

**Comment by justinbiebermusic** [comment]
I'm using php.

**Comment by cryptoapi** [comment]
You can add in php code -
If (run_sql("select paymentID from crypto_payments where orderID ='-your file id-'")) echo "File Sold".

Table **crypto_payments** stores data of received payments

**Comment by justinbiebermusic** [comment]
how can I get orderID ='-your file id-'"))

my file id?

**Comment by cryptoapi** [comment]
Your orderID. It can be fileID if you use it as orderID.

```
 // All Default Configuration variables
    $options = array(
            "public_key"  => "",
            "private_key" => "",
            **"orderID"     => $orderID,**
            "userID"      => $userID,   // optional
            "userFormat"  => "COOKIE",  // SESSION, IPADDRESS
            "amount"      => 0,
            "amountUSD"   => 0,
            "period"      => "",    // 2 HOUR, 1 DAY, 1 MONTH, NOEXPIRY, etc..
            "iframeID"    => "",    // optional
            "language"    => "EN"
    );

    // Initialise Payment Class
    $box1 = new Cryptobox ($options);
    ... ...
```


https://gourl.io/api-php.html#dev

**Comment by justinbiebermusic** [comment]
<?php if (run_sql("select paymentID from crypto_payments where orderID ='$orderID'")) echo "File Sold"?>

I used this and  it says : 

Error in run_sql() - 'nme' not exists! SQL: select paymentID from crypto_payments where orderID ='b3131ee5f6ea9565b9b714cbbe72a0a5'

can we make it like if its possible when like I'm selling on x.php and when it's sold make it like

delete x.php on filezilla a show SOLD.php

**Comment by cryptoapi** [comment]
Please use 
select paymentID **as nme** from crypto_payments where orderID ='b3131ee5f6ea9565b9b714cbbe72a0a5'

**Comment by justinbiebermusic** [comment]
<?php If (run_sql("select paymentID ###### from crypto_payments where orderID ='##########")) echo "File Sold">

I didn't understand the "#" parts. I'm sorry asking a lot but really need it. how can I make them get auto orderID for each sell.php pages and whats as nme part?

**Comment by cryptoapi** [comment]
You need manually generate your orderID and save in DB. After submit to payment box this orderID

**Comment by justinbiebermusic** [comment]
I mean I already bought my file for test. so I have an orderID on my DB. but I'm asking for how can I do it in php.

like think

example : www.site.com/forsalefile1.php

when u buy this one it's generating automatic OrderID if I do it $orderID isn't this get my OrderID who bought it automatically from DB?

<?php If (run_sql("select paymentID from crypto_payments where orderID ='$orderID'")) echo "File Sold">

so this code doing when someone bought this file checking orderID from DB for the samefile. then should be say File SOLD.

but it says 

Error in run_sql() - 'nme' not exists! SQL: select paymentID from crypto_payments where orderID ='b3131ee5f6ea9565b9b714cbbe72a0a5'

So I don't write orderID manually. it's automatically getting from DB when I write $orderID
 
but why I'm getting an error like that.

**Comment by justinbiebermusic** [comment]
ok man just find a way. it's works rn. but I have a little question do you know any code for redirect to page like

<a>LINK</a> 

when u click to link check if x.php available if it's available redirect to x.php if not redirect to sold.php

**Comment by justinbiebermusic** [comment]
okay just fixed. Thanks for your help!

**Comment by justinbiebermusic** [comment]
I just made an custom 404 page so when it's not found it will show my page. 

My 404 page is like File sold. so when someone buy it it will delete the file and buy page then other people will see my custom php file like it's sold.

$path		    = "foldername/$filename";

<?php If (run_sql("select paymentID as nme from crypto_payments where orderID ='$orderID'")) unlink("$path");?>
<?php If (run_sql("select paymentID as nme from crypto_payments where orderID ='$orderID'")) unlink("filebuy1.php");?>

filebuy1.php is this page who bought the file.

But I have an problem when I do it it's automatically delete before buyer is download.  I have 2 ideas.

1 : this php command should wait 2-3 min after someone bought.
2 : this php should count download so when someone download the file it will be +1 then this unlink command will start.

how can I do this?
