### ISSUE TITLE
Refund Request

### ISSUE THREAD

**Issue by K5rovski** [cryptoapi/Payment-Gateway#37]
Hi GoUrl,

This is the second time im contacting you, im getting plenty worried.
I made a payment on minersdepo.com website, which is clearly used to scam people from their money.

I don't know what is your verification method for your partners , but this is very troubling, I need to know you are receiving these messages, and are working on my case ?

This is the data that you might need to recall the transaction with the given id.
[Transaction 0484782f3ef5c91bb03b23b3434bdeebee498c1bda8685db051c1737031f4d05 | Blockchain Explorer1.pdf](https://github.com/cryptoapi/Payment-Gateway/files/6478618/Transaction.0484782f3ef5c91bb03b23b3434bdeebee498c1bda8685db051c1737031f4d05.Blockchain.Explorer1.pdf)

https://drive.google.com/drive/folders/1yTwn8QzyPxrzfFs5r8MzIcj_lSlyb8JT?usp=sharing

Will you refund this order, or are you supporting scam websites in your service ?
Tell me what additional info you need, and what is your process for refunding payments in your service.

Expecting good news, 
Kristijan.

**Comment by cryptoapi** [comment]
Please contact customer service - https://gourl.io/view/contact/Contact_Us.html

**Comment by michaelsomerville** [comment]
> Hi GoUrl,
> 
> This is the second time im contacting you, im getting plenty worried.
> I made a payment on minersdepo.com website, which is clearly used to scam people from their money.
> 
> I don't know what is your verification method for your partners , but this is very troubling, I need to know you are receiving these messages, and are working on my case ?
> 
> This is the data that you might need to recall the transaction with the given id.
> [Transaction 0484782f3ef5c91bb03b23b3434bdeebee498c1bda8685db051c1737031f4d05 | Blockchain Explorer1.pdf](https://github.com/cryptoapi/Payment-Gateway/files/6478618/Transaction.0484782f3ef5c91bb03b23b3434bdeebee498c1bda8685db051c1737031f4d05.Blockchain.Explorer1.pdf)
> 
> https://drive.google.com/drive/folders/1yTwn8QzyPxrzfFs5r8MzIcj_lSlyb8JT?usp=sharing
> 
> Will you refund this order, or are you supporting scam websites in your service ?
> Tell me what additional info you need, and what is your process for refunding payments in your service.
> 
> Expecting good news,
> Kristijan.

You realise that is open source code right ? Why would you contact the developers of the code to get a refund that they can't control. Seems a little odd. That would be like contacting the makers of tires for a refund on the car you purchased. I am not involved in the project you are having issues with, but just seen this here and thought man this dude is having a time.
