### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by EasycryptosTeam** [cryptoapi/Payment-Gateway#38]
Hello, I am a gourl plugin user a long time ago, yesterday I downloaded and installed the pluging again on my website.
What I found was a little sad, 'cause I found several death coins such as PEERCOIN, UNIT, MUNI etc.

I think this is agreat job, but coin voting was ended, I think this amazing project must have more coins, I have a list if you wanna take in mind.

* ETH
* TRON and some of its tokens as WIN, BTT  among other good projects.
* BNB and some of its tokens as BANANA, CAKE among other good projects.
* ADA and some of its tokens as good projects.
* LINK [CHAINLINK]
* TETHA
* IOTA

What I want to be clear is this **payment gateway is the best one in market**, do not let it die, update the coin list, allow us to vote new coins and let´s grow to the moon!

**Comment by cryptoapi** [comment]
Yes, it is Live.

**Comment by EasycryptosTeam** [comment]
@cryptoapi  what do You think about adding new coins as the ones I mentioned?
