### ISSUE TITLE
Is the project alive?

### ISSUE THREAD

**Issue by BaseMax** [cryptoapi/Payment-Gateway#43]
Hello,

Is the project still suitable for production? what happened? Don't have any plans to support and continue?
If not, then what is the new website?
I mean, https://gourl.io/bitcoin-payment-gateway-api.html

**Comment by carloshlemusm** [comment]
Hi, I'm user for GoURL, and the payment gateway api works for me. But i'm not sure that support continue

**Comment by cryptoapi** [comment]
The project is alive. Our gateway is operating normally.
