### ISSUE TITLE
Invalid Private Key

### ISSUE THREAD

**Issue by ShamaIow** [cryptoapi/Payment-Gateway#44]
I'm getting an error like this **Invalid Private Key - _{key}_ in variable $cryptobox_private_keys, file cryptobox.config.php.**. I just don't know what to put on it because the private keys are already defined in the [example](https://github.com/cryptoapi/Payment-Gateway/blob/master/example_basic.php) line 87. Someone can help me please?

**Comment by cryptoapi** [comment]
Create new bitcoin/litecoin/etc payment boxes and get free Gourl Private/Public Keys here 
 -
https://gourl.io/editrecord/coin_boxes/0
