### ISSUE TITLE
Hello I need help.

### ISSUE THREAD

**Issue by Pocker88** [cryptoapi/Payment-Gateway#46]
I have some issue with payment.. answer on my email. My nickname FMDOSE. Letter about transaction with 0.01652907 LTC

**Comment by cryptoapi** [comment]
please contact on https://gourl.io/view/contact/Contact_Us.html

**Comment by Pocker88** [comment]
I get mess from you and send my address to you but NOTHING... Pls help me.
![Screenshot_2023-08-22-13-00-40-21_e307a3f9df9f380ebaf106e1dc980bb6](https://github.com/cryptoapi/Payment-Gateway/assets/79075067/2b33da56-1c6c-4615-ac0e-b652d310758e)
