### ISSUE TITLE
Mysql Erro

### ISSUE THREAD

**Issue by gaurav99t** [cryptoapi/Payment-Gateway#8]
Why do i always get this error?

?bitcoinMySQL Error: Table 'gourl.crypto_payments' doesn't exist; SQL: SELECT paymentID, amount, amountUSD, txConfirmed, txCheckDate, txDate, processed, boxType FROM crypto_payments WHERE boxID = 5424 && orderID = 'premium_membership' && userID = 'xzx' && txDate >= DATE_SUB('2017-06-06 10:14:57', INTERVAL 1 MONTH) ORDER BY txDate DESC LIMIT 1

**Comment by cryptoapi** [comment]
You need to create mysql table **crypto_payments**

Instruction - 
https://github.com/cryptoapi/Payment-Gateway#mysql-table
