### ISSUE TITLE
Get realtime price

### ISSUE THREAD

**Issue by gaurav99t** [cryptoapi/Payment-Gateway#9]
how is it possible to just check real time price for any crypto coin?

**Comment by cryptoapi** [comment]
Gourl Bitcoin/Altcoin Gateway use bitcoin prices from - https://www.bitstamp.net/ (update every 10min)
Altcoin prices from poloniex.com https://poloniex.com/exchange#btc_eth

Current live prices - https://gourl.io/bitcoin-payment-gateway-api.html (right column)
